# vim ft=yaml
language: python
sudo: false
python:
  - "2.7"
  - "3.5"

install:
  - pip install pip --upgrade
  - pip install pytest --upgrade
  - pip install codecov runipy
  - pip install -e '.'
  - pip install flake8

script:
  - PYTHONPATH=$PWD coverage run `which py.test` grabbit
  - python setup.py install  # test installation
  - cd examples; PYTHONPATH=.. runipy *.ipynb  # test example notebooks to run and not fail
  # for now flaking only the stub.py
  # - flake8 grabbit

after_success:
  - codecov

